Upload logs separately

diff --git a/.github/workflows/templates/upload.yml b/.github/workflows/templates/upload.yml
--- a/.github/workflows/templates/upload.yml
+++ b/.github/workflows/templates/upload.yml
@@ -3,9 +3,21 @@
       if: always()
       shell: bash
       run: |
-        curl https://report.ci/report.py > report.py
-          python report.py \
-          --include-as-junit 'artifacts/xml-unittests-output/*.xml' \
-          --log-as-python 'artifacts/logs/*.log'
-          --merge ".*" \
-          --name="{display_name}" || echo "Failed to upload test results"
+        if [ ! -f report.py ]; then
+          curl https://report.ci/report.py > report.py
+        fi
+        python report.py \
+        --include-as-junit 'artifacts/xml-unittests-output/*.xml' \
+        --merge ".*" \
+        --name="{display_name} Tests" || echo "Failed to upload test results"
+
+    - name: Upload Logs
+      if: always()
+      shell: bash
+      run: |
+        if [ ! -f report.py ]; then
+          curl https://report.ci/report.py > report.py
+        fi
+        python report.py \
+        --log-as-python 'artifacts/logs/*.log'
+        --name="{display_name} Logs" || echo "Failed to upload logs"
